<div class="container_12">

<h2>Warum?</h2>
<p>Seit dem 1.1.2010 m&uuml;ssen Stromversorger ihren Kunden f&uuml;r Neubauten so genannte &quot;intelligente Stromz&auml;hler&quot; (Smart Meter) anbieten. Der Kunde soll dadurch seinen Stromverbrauch analysieren und optimieren k&ouml;nnen.<br><br>
Die dabei anfallenden Daten (&quot;Stromverbrauchsprofil&quot;) erlauben einen sehr detallierten Einblick in den Tagesablauf des Nutzers (wann steht er auf? wann geht er in's Bett? wann kocht er? wie oft verwendet er seine Sp&uuml;lmaschine? ver&auml;ndert sich sein Verhalten? ...). Darum sollten die Daten ausschlie&szlig;lich f&uuml;r den Nutzer selbst zur Verf&uuml;gung stehen - und das geht nur, wenn man sich den Smart Meter selbst baut. Mit einem Materialeinsatz von ca. EUR 100, etwas Geschick und Zeit l&auml;sst sich das mit Hilfe eines Standard-&micro;C-Moduls aufbauen.</p>

<h2>Wie kann ich mir selbst einen volkszaehler bauen?</h2>
<p>volkszaehler.org ist ein OpenSource Projekt, dessen Hard- und Software unter der <acronym title="GNU General Public License">GPL</acronym> lizenziert sind. Jeder darf es kostenlos nutzen und uns bei der <a href="http://wiki.volkszaehler.org/development/start">Entwicklung</a> <a href="http://wiki.volkszaehler.org/contribute">unterst&uuml;tzen</a>.</p>
<ul>
	<li><span>Im <a href="http://wiki.volkszaehler.org/">Wiki</a> sammeln wir alle wichtigen Infos f&uuml;r Entwickler ebenso wie f&uuml;r Anwender.</span></li>
	<li><span>Willst du aktiv einsteigen gibt es noch eine <a href="mailto:volkszaehler-dev-subscribe@lists.volkszaehler.org">Mailingliste</a> mitsamt <a href="http://volkszaehler.org/pipermail/volkszaehler-dev/">Archiv</a>, die du abonnieren solltest, um auf dem aktuellen Stand zu bleiben.</span></li>
	<li><span>Der Quelltext des Projekts wird mit Git gepflegt und ist bei <a href="http://github.com/volkszaehler/volkszaehler.org/">GitHub</a> gehostet.</span></li>
</ul>

</div>
