<div class="container_12">

<ul>
	<li>100% Open-Source</li>
	<ul>
		<li>kostenlos</li>
		<li>offene Protokolle</li>
		<li>erweiterbar</li>

	</ul>
	<li>minmale Anforderungen (LAMP-Stack)</li>
	<li>flexibele Verwaltungsmöglichkeiten</li>
	<li>Verbrauchs & Kostenprognose</li>
	<li>verschiedenste Messgrößen</li>
	<ul>
		<li>Strom</li>
		<li>Wasser</li>
		<li>Gas</li>
		<li>Betriebsstunden</li>
		<li>Temperatur</li>
	</ul>
</ul>

</div>
