<div class="container_12">

<ul>
	<li><span>100% Open-Source</span></li>
	<ul>
		<li><span>kostenlos</span></li>
		<li><span>offene Protokolle</span></li>
		<li><span>erweiterbar</span></li>

	</ul>
	<li><span>minmale Anforderungen (LAMP-Stack)</span></li>
	<li><span>flexibele Verwaltungsmöglichkeiten</span></li>
	<li><span>Verbrauchs & Kostenprognose</span></li>
	<li><span>verschiedenste Messgrößen</span></li>
	<ul>
		<li><span>Strom</span></li>
		<li><span>Wasser</span></li>
		<li><span>Gas</span></li>
		<li><span>Betriebsstunden</span></li>
		<li><span>Temperatur</span></li>
	</ul>
</ul>

</div>
