<div class="teaser">
        <div class="container_12">
                <div class="grid_4">
                        <h2>Stromverbrauch im &Uuml;berblick</h2>
                        <p>volkszaehler.org ist ein freier Smart Meter (hier: intelligenter Stromzähler) im Selbstbau. Die anfallenden Stromprofile bleiben dabei unter der Kontrolle des Nutzers.</p>
                        <a href="https://demo.volkszaehler.org/frontend/?uuid=6836dd20-00d5-11e0-bab1-856ed5f959ae" class="teaser_button">Jetzt ausprobieren!</a>
                </div>
                <div class="grid_8">
                        <div class="screenshot floatRight">
                                <img src="images/screenshot.png" alt="screenshot" />
                        </div>
                </div>
        </div>
</div>
</div>
<div class="container_12">
        <div class="grid_6 floatLeft"><div class="box">
                <h3>Aktuelles</h3>
                <p><strong>Wir suchen Helfer!</strong> <br />
                Die Arbeit an volkszaehler.org erfordert eine Menge Zeit. Wenn du denkst, du kannst etwas zu dem Projekt beitragen, sieh doch mal nach, was es noch zu tun gibt.</p>
        </div></div>
        <div class="grid_3"><div class="box">
                <h3>Wiki</h3>
                <p>Hier findest du alles, was es über volkszaehler.org zu wissen gibt. Anleitungen, Hintergrundwissen, etc</p>
        </div></div>
        <div class="grid_3"><div class="box">
                <h3>Anleitung</h3>
                <p>Kurz und knapp, eine Schritt-für-Schritt Anleitung für jeden mit ein wenig handwerklichem Geschick.</p>
        </div></div>
        <div class="grid_3"><div class="box">
                <h3>Mitwirken</h3>
                <p>Du bist Entwickler und willst helfen volkszaehler.org zu verbessern? Den kompletten Quelltext findest du in unserem GitHub Repository.</p>
        </div></div>
        <div class="grid_3"><div class="box">
                <h3>Mailing-Liste</h3>
                <p>Du interessierst dich für die Entwicklung von volkszaehler.org? Abonniere die Mailing-Liste und bleibe immer auf dem neusten Stand.</p>
        </div></div>
        <div class="grid_6"><div class="box">
                <h3>Twitter</h3>
		<div id="tweets"></div>
        </div></div>
</div>
<script type="text/javascript" src="js/jquery-1.6.3.min.js"></script>
<script type="text/javascript" src="js/jquery.tweet.js"></script>
<script>
 $('#tweets').tweet({
        avatar_size: 16,
        count: 6,
        query: 'from:volkszaehler OR @volkszaehler',
        loading_text: 'searching twitter...'
      });
</script>
