<div class="teaser">
        <div class="container_12">
                <div class="grid_4">
		<h2>Stromverbrauch im &Uuml;berblick</h2>
			<p>volkszaehler.org ist ein freies Smart Meter im Selbstbau.<br />Der Nutzer behält dabei die vollständige Kontrolle über die anfallenden Strom, Wasser & Gaskosten.</p>
			<a href="https://demo.volkszaehler.org/frontend/?uuid=6836dd20-00d5-11e0-bab1-856ed5f959ae" class="button">Jetzt ausprobieren!</a>
		</div>
		<div class="grid_8">
			<div class="screenshot floatRight">
				<a href="http://wiki.volkszaehler.org/_media/software/releases/screenshot-0.2.png">
					<img src="images/screenshot.png" alt="screenshot" />
				</a>
			</div>
                </div>
	</div>
</div>
<div class="container_12 row1 sep-bot">
        <div class="grid_3"><div class="box">
                <h3><a href="http://wiki.volkszaehler.org">Wiki</a></h3>
                <p>Hier findest du alles, was es über volkszaehler.org zu wissen gibt. Anleitungen, Hintergrundwissen, etc.</p>
		<a class="bottom" href="http://wiki.volkszaehler.org"><u>zum Wiki</u></a>
        </div></div>
        <div class="grid_3"><div class="box box-sep">
                <h3><a href="http://wiki.volkszaehler.org/howto/getstarted">Anleitung</a></h3>
                <p>Kurz und knapp, eine Schritt-für-Schritt Anleitung für jeden mit ein wenig handwerklichem Geschick.</p>
		<a class="bottom" href="http://wiki.volkszaehler.org/howto/getstarted"><u>zur Anleitung</u></a>
        </div></div>
		 <div class="grid_6 floatLeft"><div class="box box-sep">
	                <h3>Aktuelles</h3>
	                <p><strong>Wir suchen Helfer!</strong><br />
	                Die Arbeit an volkszaehler.org erfordert eine Menge Zeit. Wenn du denkst, du kannst etwas zu dem Projekt beitragen, sieh doch mal nach, was es noch zu tun gibt.</p>
			<a class="bottom" href="http://wiki.volkszaehler.org/contribute"><u>mitmachen!</u></a>
	        </div></div>
</div>
<div class="container_12 row2">
		<div class="grid_3"><div class="box video">
                <h3><a href="/unfuck">Vortrag</a></h3>
                <p>Auf der <a href="http://unfuck.eu/2011">UnFUCK '11</a> hat Justin seinen neuen Vortrag zum volkszaehler präsentiert:</p>
		<div class="bottom">
			<a href="./unfuck"><img style="margin-top: 8px" src="images/unfuck_thumb.png" alt="zum Vortrag" /></a>
			<p class="licence">
				&copy; <a href="http://mediathek.hs-furtwangen.de">Hochschule Furtwangen</a>
			</p>
		</div>
        </div></div>
        <div class="grid_3"><div class="box box-sep interview">
                <h3>Interview</h3>
                <p>Während des elektro:camp(&laquo;2011:5&raquo;) entstand folgendes Interview mit Ingo Ebel von RadioTux. Justin gibt einen kurzen Überblick über Smart Metering und das Projekt.</p>
		<div class="bottom">
			<p><audio controls="controls">
				<source type="audio/mp3" src="http://archiv.radiotux.de/interviews/2011-05-28.RadioTux.Volkszaehler.mp3"></source>
				<source type="audio/ogg" src="http://archiv.radiotux.de/interviews/2011-05-28.RadioTux.Volkszaehler.ogg"></source>
				Bitte einen HTML5 Browser verwenden
			</audio></p>
			<p class="licence">
				<a href="http://creativecommons.org/licenses/by-nc-sa/3.0/">
					<img src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" alt="Creative Commons License">
				</a>&nbsp;
				<a href="http://blog.radiotux.de/2011/06/29/interview-volkszaehler-org/">&copy; RadioTux</a>
			</p>
		</div>
        </div></div>
        <div class="grid_6"><div class="box box-sep twitter">
                <h3>Twitter</h3>
		<div id="tweets"></div>
        </div></div>
</div>
<script type="text/javascript" src="js/jquery-1.6.3.min.js"></script>
<script type="text/javascript" src="js/jquery.tweet.js"></script>
<script>
 $('#tweets').tweet({
        avatar_size: 16,
        count: 5,
        query: 'from:volkszaehler OR @volkszaehler',
	username: 'volkszaehler',
        loading_text: 'searching twitter...'
      });
</script>
