<div class="container_12">
	<object width="600" height="800">
		<param value="http://mediathek.hs-furtwangen.de/ext/player/player.swf" name="movie">
		<param value="true" name="allowFullScreen">
		<param value="always" name="allowscriptaccess">
		<param value="config=http://mediathek.hs-furtwangen.de/ext/player/p.xml&amp;file=c6b03aefecf1d099027a5fa33c9acc26.mp4" name="flashvars">
		<embed width="800" height="600" flashvars="config=http://mediathek.hs-furtwangen.de/ext/player/p.xml&amp;file=c6b03aefecf1d099027a5fa33c9acc26.mp4&amp;screencolor=ffffff&amp;controlbar.idlehide=true&amp;image=images/unfuck.png" allowfullscreen="true" allowscriptaccess="always" type="application/x-shockwave-flash" src="http://mediathek.hs-furtwangen.de/ext/player/player.swf">
	</object>
	<p><a href="http://volkszaehler.org/volkszaehler.org.2011-04-16.pdf">Folien zum Vortrag (PDF, 4 MB)</a></p>
</div>
